### PR TITLE
Added folder "doc", which is needed by build.xml by default…

### PR DESCRIPTION
**Pull request by tschoening**
… and was available in the original files at Sourceforge as well.

### CODE REVIEW

**Comment by tschoening** [comment]
Yes, the docs are partly outdated, but not everything mentioned there is wrong. So in my opinion it's better to keep them and remove the wrong parts individually while people are recognizing them vs. having essentially no docs at all. As can be seen in build.xml, some kind of "docs" was intended anyway and I guess the original project just didn't reach a point being able to provide those. In the end, it's the same argument why you didn't start from scratch implementing kSar2. :-)

docs/README is very different from README.md, because the former gets part of the binary distribution. They are not intended to replace each other. It's the same with the LICENSE file, though in this case both files are identical.

The doc|docs folder is required because it seems to be mentioned at all and used by default in build.xml:

    <target name="-post-jar">
    [...]
    <zip destfile="${store.zip}" >
            <zipfileset dir="contrib" prefix="contrib" />
            <zipfileset dir="doc" prefix="doc" />
            <zipfileset file="${store.jar}" />
    </zip>

> C:\Users\[...]\ksar2>ant clean && ant
> [...]
> BUILD FAILED
> C:\Users\tschoening\Documents\Repos\Git\GitHub\ksar2\build.xml:121: C:\Users\tschoening\Documents\Repos\Git\GitHub\ksar2\doc does not exist.

**Comment by ppalucha** [comment]
Closing; build system changed to Maven, so doc folder is not required anymore.

**Comment by tschoening** [comment]
A required `doc` folder is only one part of this issue, the other is deleting the old docs entirely. Do you really think it's a good idea to not provide any documentation at all anymore?

**Comment by ppalucha** [comment]
I don't want to bring documentation that is not relevant to current code. If somebody is interested in historical docs, original project is available at sf.net.

**Pull request closed without merging**
